### ISSUE TITLE
Crash - [Forge 14.23.0.2508] [MC 1.12.2] - 

### ISSUE THREAD

**Issue by XvSkItZvX** [BlakeBr0/ExtendedCrafting#6]
Just a heads up and as much info as I can provide. 
Forge 14.23.0.2508 is just a few hours old at this point so it's no surprise and rolling back to the previous version kept it from crashing. Log listed below. Thanks!

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterSprintingCore (BetterSprinting  MC-1.12.2  v2.1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MMFMLCorePlugin (MultiMine-1.12.1.jar)
  LoadingPlugin (Quark-r1.3-111.jar)
  DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.1-1.12-anarchy.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 10/7/17 6:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extended Crafting (extendedcrafting)
Caused by: java.lang.NoClassDefFoundError: com/blakebr0/cucumber/registry/ModRegistry
	at com.blakebr0.extendedcrafting.ExtendedCrafting.<clinit>(ExtendedCrafting.java:29)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:522)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
Caused by: java.lang.ClassNotFoundException: com.blakebr0.cucumber.registry.ModRegistry
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 49 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1808300024 bytes (1724 MB) / 2060255232 bytes (1964 MB) up to 4207738880 bytes (4012 MB)
	JVM Flags: 25 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2508 Optifine OptiFine_1.12.2_HD_U_C6 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version                  | Source                                        | Signature                                |
	|:----- |:--------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                   | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UC    | mcp                         | 9.42                     | minecraft.jar                                 | None                                     |
	| UC    | FML                         | 8.0.99.99                | forge-1.12.2-14.23.0.2508-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                       | 14.23.0.2508             | forge-1.12.2-14.23.0.2508-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | betterfonts                 | 1.9.1                    | minecraft.jar                                 | None                                     |
	| UC    | foamfixcore                 | 7.7.4                    | minecraft.jar                                 | None                                     |
	| UC    | rpghud                      | 3.6.6.2                  | [1.12] RPG-HUD-3.6.6.2.jar                    | None                                     |
	| UC    | jaopcacustom                | 1.12-2.2.0.8             | JAOPCACustom-1.12-2.2.0.8.jar                 | None                                     |
	| UC    | jaopca                      | 1.12-2.2.3.47            | JAOPCA-1.12-2.2.3.47.jar                      | None                                     |
	| UC    | jaopcaoc                    | 1.0.6                    | AOBDOC-1.12.2-1.0.6.jar                       | None                                     |
	| UC    | crafttweaker                | 4.0.8                    | CraftTweaker2-1.12-4.0.8.jar                  | None                                     |
	| UC    | mtlib                       | @VERSION@                | MTLib-3.0.0.jar                               | None                                     |
	| UC    | modtweaker                  | 4.0.3                    | modtweaker-4.0.3.jar                          | None                                     |
	| UC    | jei                         | 4.8.0.105                | jei_1.12.2-4.8.0.105.jar                      | None                                     |
	| UC    | appleskin                   | 1.0.8                    | AppleSkin-mc1.12-1.0.8.jar                    | None                                     |
	| UC    | csb_armorstand              | 1.0.4                    | ArmorStandGUI-1.12-1.0.4.jar                  | None                                     |
	| UC    | quark                       | r1.3-111                 | Quark-r1.3-111.jar                            | None                                     |
	| UC    | autoreglib                  | 1.3-13                   | AutoRegLib-1.3-13.jar                         | None                                     |
	| UC    | baubles                     | 1.5.1                    | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UC    | bedbugs                     | @VERSION@                | BedBugs-1.12-1.0.1.jar                        | None                                     |
	| UC    | betteradvancements          | 0.0.3.12                 | BetterAdvancements-1.12.1-0.0.3.12.jar        | None                                     |
	| UC    | bettersprinting             | 2.1.0                    | BetterSprinting  MC-1.12.2  v2.1.0.jar        | None                                     |
	| UC    | blockdrops                  | 1.3.0                    | blockdrops-1.12-1.3.0.jar                     | None                                     |
	| UC    | bookshelf                   | 2.2.464                  | Bookshelf-1.12.2-2.2.464.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | carryon                     | 1.6                      | CarryOn MC1.12 v1.6.jar                       | None                                     |
	| UC    | redstoneflux                | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | cofhcore                    | 4.3.5                    | CoFHCore-1.12-4.3.5.13-universal.jar          | None                                     |
	| UC    | cofhworld                   | 1.0.1                    | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UC    | controlling                 | 3.0.3                    | Controlling-3.0.3.jar                         | None                                     |
	| UC    | craftingtweaks              | 8.1.5                    | CraftingTweaks_1.12.1-8.1.5.jar               | None                                     |
	| UC    | ctgui                       | 1.0.0                    | CraftTweaker2-1.12-4.0.8.jar                  | None                                     |
	| UC    | crafttweakerjei             | 2.0.0                    | CraftTweaker2-1.12-4.0.8.jar                  | None                                     |
	| UC    | defaultoptions              | 9.2.4                    | DefaultOptions_1.12.1-9.2.4.jar               | None                                     |
	| UC    | dig                         | 1.1.11                   | Dig-1.1.11_1.12.1.jar                         | None                                     |
	| UC    | dynamiclights               | 1.4.6                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_onfire        | 1.0.7                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_creepers      | 1.0.6                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_dropitems     | 1.1.0                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_entityclasses | 1.0.1                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_mobequipment  | 1.1.0                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_flamearrows   | 1.0.1                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_floodlights   | 1.0.3                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_otherplayers  | 1.0.9                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dynamiclights_theplayer     | 1.1.3                    | DynamicLights-1.12.1.jar                      | None                                     |
	| UC    | dsurround                   | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UC    | presets                     | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar        | None                                     |
	| UC    | csb_ench_table              | 1.1.2                    | EnchantingTable-1.12-1.1.2.jar                | None                                     |
	| UC    | enhancedvisuals             | 1.0                      | EnhancedVisuals v1.1.4 mc1.12.jar             | None                                     |
	| UE    | extendedcrafting            | 1.0.3                    | extendedcrafting-1.12-1.0.3.jar               | None                                     |
	| UC    | foamfix                     | 0.8.0-1.12               | foamfix-0.8.1-1.12-anarchy.jar                | None                                     |
	| UC    | ichunutil                   | 7.0.2                    | iChunUtil-1.12.2-7.0.2.jar                    | None                                     |
	| UC    | ftbl                        | 4.1.6                    | FTBLib-4.1.6.jar                              | None                                     |
	| UC    | ftbu                        | 4.1.6                    | FTBUtilities-4.1.6.jar                        | None                                     |
	| UC    | fw                          | 1.6.0                    | FullscreenWindowed-1.12-1.6.0.jar             | None                                     |
	| UC    | gamestages                  | 1.0.65                   | GameStages-1.12.2-1.0.65.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | guideapi                    | 1.12-2.1.4-57            | Guide-API-1.12-2.1.4-57.jar                   | None                                     |
	| UC    | helpfixer                   | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                   | None                                     |
	| UC    | waila                       | 1.8.20                   | Hwyla-1.8.20-B35_1.12.jar                     | None                                     |
	| UC    | initialinventory            | 2.0.2                    | InitialInventory-3.0.0.jar                    | None                                     |
	| UC    | inventorytweaks             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | itemzoom                    | 1.10                     | itemzoom_1.12.1-1.10.jar                      | None                                     |
	| UC    | oredictinit                 | 1.12-2.2.0.55            | JAOPCA-1.12-2.2.3.47.jar                      | None                                     |
	| UC    | jeiintegration              | 1.4.2.31                 | jeiintegration_1.12.1-1.4.2.31.jar            | None                                     |
	| UC    | jepb                        | 1.2.1                    | jepb-1.12-1.2.1.jar                           | None                                     |
	| UC    | journeymap                  | 1.12.1-5.5.0             | journeymap-1.12.1-5.5.0.jar                   | None                                     |
	| UC    | jeresources                 | 0.8.3.23                 | JustEnoughResources-1.12-0.8.3.23.jar         | None                                     |
	| UC    | kc                          | 1.12                     | knobcontrol-1.12-4.0.16.jar                   | None                                     |
	| UC    | minemenu                    | 1.6.2                    | MineMenu-1.12.2-1.6.2-universal.jar           | None                                     |
	| UC    | mobamputation               | 7.0.0                    | MobAmputation-1.12.2-7.0.0.jar                | None                                     |
	| UC    | mobstages                   | 1.0.5                    | MobStages-1.12.2-1.0.5.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | moredefaultoptions          | 1.12-0.0.2               | moredefaultoptions-1.12-0.0.2.jar             | None                                     |
	| UC    | mousetweaks                 | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
	| UC    | multimine                   | 1.5.7                    | MultiMine-1.12.1.jar                          | None                                     |
	| UC    | neat                        | 1.4-15                   | Neat 1.4-15.jar                               | None                                     |
	| UC    | netherportalfix             | 1.0                      | NetherPortalFix_1.12-5.3.1.jar                | None                                     |
	| UC    | neid                        | 1.5.4.2                  | NotEnoughIDs-1.5.4.2.jar                      | None                                     |
	| UC    | oreberries                  | 0.3.2                    | oreberries-1.12.x-0.3.2.jar                   | None                                     |
	| UC    | cobwebs                     | 1.0.3                    | realistic-cobwebs-1.12.1-1.0.3.jar            | None                                     |
	| UC    | reap                        | 1.5.0                    | reap-1.5.0.jar                                | None                                     |
	| UC    | rockycore                   | 0.3.0                    | rockycore-1.12-0.3.0.jar                      | None                                     |
	| UC    | soundfilters                | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| UC    | stg                         | 1.12-1.2.1               | stg-1.12-1.2.1.jar                            | None                                     |
	| UC    | tellme                      | 0.5.4                    | tellme-1.12.1-0.5.4.jar                       | 2b03e1423915a189b8094816baa18f239d576dff |
	| UC    | thermalfoundation           | 2.3.5                    | ThermalFoundation-1.12-2.3.5.14-universal.jar | None                                     |
	| UC    | tombstone                   | 1.3.8                    | tombstone-1.3.8.jar                           | None                                     |
	| UC    | wailaharvestability         | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| UC    | wailastages                 | 1.0.22                   | WailaStages-1.12.2-1.0.22.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | waterstrainer               | 3.2.0                    | WaterStrainer-1.12-3.2.0.jar                  | None                                     |
	| UC    | wawla                       | 2.5.245                  | Wawla-1.12.2-2.5.245.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | wit                         | 1.0.25                   | WIT-1.12-1.0.25-44.jar                        | None                                     |
	| UC    | wrapup                      | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                         | None                                     |

	Loaded coremods (and transformers): 
BetterSprintingCore (BetterSprinting  MC-1.12.2  v2.1.0.jar)
  chylex.bettersprinting.system.core.TransformerEntityPlayerSP
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MMFMLCorePlugin (MultiMine-1.12.1.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (Quark-r1.3-111.jar)
  vazkii.quark.base.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  atomicstryker.dynamiclights.common.DLTransformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
  cubex2.ttfr.BFClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.1-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.69' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 385.69
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by BlakeBr0** [comment]
Do you not have Cucumber installed?

**Comment by XvSkItZvX** [comment]
Yes and no...and completely my mistake in reporting it.

This crash report does not have cucumber installed, which I managed catch on after the initial crash and promptly installed. It crashed without triggering the dependency error though.

With cucumber installed, it still crashed on load and didn't create a crash report.

I do apologize for not being more clear about the events, I had other little distractions at the time and honestly wasn't even sure how many times I crashed it....

Thinking back though it could be somewhere between Extended Crafting or Cucumber as I had installed both mods individually. First Extended Crafting (resulting in the above error) then Cucumber (Resulting in a crash without log) and then rolling back my Forge version and successfully loading the game. 

if there is anything else else I can do or provide you I'm more than willing to help on my end.

**Comment by BlakeBr0** [comment]
I can load the mods just fine on 2509. Does the crash happen with only my mods installed?

**Comment by XvSkItZvX** [comment]
Peculiar indeed...
The version of Forge I was having issue with was actually 2508 (it's still Oct 7th here so I won't get 2509 until tomorrow)...But I did just check to see how 2508 worked with just Extended Crafting and Cucumber installed (since I had to wait anyways) and it worked without issue.

But I decided that since you had 2509 already I'd jump in my time machine and try with it an all mods enabled again and it worked well too...

Given that 2508 was so short lived, and it works completely in 2509 I don't think it will be a problem. If you can give me any advice as to how to pin point what actually caused the initial error I'd be able to inform any other developer involved. Otherwise, likely a nonissue at this point.

Thanks for you quick response, sorry for taking up your time for a false alarm lol. Keep up the great work.

**Comment by BlakeBr0** [comment]
If there was no crash log you can look at the 'latest' file in the logs folder to find any errors. Since it seems to be fixed it may not be something to worry about, unless it happens again of course.

Glad you like the mod 👍
